language: android
sudo: required
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
  global:
    # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=10
    - MALLOC_ARENA_MAX=2

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-21

  # Emulator for the tests
  - sys-img-armeabi-v7a-android-21

addons:
  apt_packages:
    - pandoc
  artifacts:
    paths:
      - $(git ls-files -o | grep build/outputs | tr "\n" ":")

before_script:
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace -x MapboxAndroidSDK:connectedAndroidTest
  - rm /home/travis/.gradle/caches/2.2.1/plugin-resolution/cache.properties.lock

after_failure:
  - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'

after_script:
  # print lint results details
  - for f in app/build/outputs/lint-results.html; do pandoc $f -t plain; done
  - for f in data/build/outputs/lint-results.html; do pandoc $f -t plain; done
